replicaCount: 2

image:
  repository: 600627353694.dkr.ecr.ap-south-1.amazonaws.com/itay/short-url
  tag: "v1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: shorturl-app.ddns.net
      paths:
        - path: /
          pathType: Prefix

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: MONGO_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongodb-credentials
        key: username
  - name: MONGO_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb-credentials
        key: password
  - name: MONGO_DATABASE
    value: "urlshortener"
