apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true