mongodb:
  enabled: true
  replicaCount: 1
  architecture: standalone
  auth:
    rootUser: mongodb_admin
    rootPassword: admin_password_123
    username: url_shortener_user
    password: app_password_123
    database: urlshortener

  persistence:
    enabled: true
    storageClass: "mongodb-gp3"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

  resources:
    limits:
      cpu: 1000m  # Increase to 1 core
      memory: 2Gi # Increase to 2GB for dev environment
    requests:
      cpu: 500m   # Increase slightly
      memory: 1Gi # Increase base memory

  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 3

  # Add startup probe to give more time for initial startup
  startupProbe:
    enabled: true
    initialDelaySeconds: 100
    periodSeconds: 30
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 15

url-shortener:
  replicaCount: 2
  image:
    repository: 600627353694.dkr.ecr.ap-south-1.amazonaws.com/itay/short-url
    tag: "latest"
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "url-shortener.local"
        paths:
          - path: /
            pathType: Prefix
