mongodb:
  enabled: true
  replicaCount: 1
  architecture: standalone
  auth:
    rootUser: mongodb_admin
    rootPassword: admin_password_123
    username: url_shortener_user
    password: app_password_123
    database: urlshortener

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 250m      # Reduced from 500m
      memory: 512Mi  # Keep this minimal for startup

  # Extend timeouts further and add debug logging
  extraEnvVars:
    - name: BITNAMI_DEBUG
      value: "true"
    - name: MONGODB_EXTRA_FLAGS
      value: "--setParameter maxTransactionLockRequestTimeoutMillis=5000 --setParameter wiredTigerConcurrentReadTransactions=128 --setParameter wiredTigerConcurrentWriteTransactions=128"

  livenessProbe:
    enabled: true
    initialDelaySeconds: 180  # 3 minutes
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 6

  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 6

  persistence:
    enabled: true
    storageClass: "mongodb-gp3"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

url-shortener:
  replicaCount: 2
  image:
    repository: 600627353694.dkr.ecr.ap-south-1.amazonaws.com/itay/short-url
    tag: "latest"
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "url-shortener.local"
        paths:
          - path: /
            pathType: Prefix
