mongodb:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  auth:
    enabled: true
    rootUser: mongodb_admin
    rootPassword: admin_password_123
    username: url_shortener_user
    password: app_password_123
    database: urlshortener

  persistence:
    enabled: true
    storageClass: "mongodb-gp3"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 6
    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 6

  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 15
    timeoutSeconds: 20

url-shortener:
  replicaCount: 2
  image:
    repository: 600627353694.dkr.ecr.ap-south-1.amazonaws.com/itay/short-url
    tag: "latest"
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "url-shortener.local"
        paths:
          - path: /
            pathType: Prefix
