mongodb:
  enabled: true
  replicaCount: 1
  architecture: standalone
  auth:
    rootUser: mongodb_admin
    rootPassword: admin_password_123
    username: url_shortener_user
    password: app_password_123
    database: urlshortener

  persistence:
    enabled: true
    storageClass: "mongodb-gp3"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  ## Add or override these to give Mongo more time to start up
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10
    periodSeconds: 20
    failureThreshold: 6

  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 20
    failureThreshold: 6

url-shortener:
  replicaCount: 2
  image:
    repository: 600627353694.dkr.ecr.ap-south-1.amazonaws.com/itay/short-url
    tag: "latest"
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: "url-shortener.local"
        paths:
          - path: /
            pathType: Prefix
