url-shortener:
  replicaCount: 1  # Fewer replicas for dev
  image:
    tag: "latest"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    hosts:
      - host: "dev.url-shortener.local"

mongodb:
  enabled: true  # Add this to ensure MongoDB is enabled
  auth:
    rootUser: mongodb_admin
    rootPassword: admin_password_123
    username: url_shortener_user
    password: app_password_123
    database: urlshortener
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    size: 1Gi