# dev.yaml
mongodb:
  replicaCount: 1
  enabled: true
  auth:
    rootUser: mongodb_admin
    rootPassword: admin_password_123
    username: url_shortener_user
    password: app_password_123
    database: urlshortener

  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  persistence:
    size: 1Gi

url-shortener:
  replicaCount: 1
  image:
    tag: "latest"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "shorturl-app.ddns.net"
        paths:
          - path: /
            pathType: Prefix
