# dev.yaml
mongodb:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  persistence:
    size: 2Gi
url-shortener:
  replicaCount: 1
  image:
    tag: "v1.0.13"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "shorturl-app.ddns.net"
        paths:
          - path: /
            pathType: Prefix
