apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - type: helm
      url: https://charts.bitnami.com/bitnami
      name: bitnami
    - type: helm
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
    - type: helm
      url: https://helm.elastic.co
      name: elastic
    - type: helm
      url: https://fluent.github.io/helm-charts
      name: fluent