apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: elasticsearch
    helm:
      values: |
        # Basic cluster settings
        clusterName: "elasticsearch"
        nodeGroup: "master"
        
        # Single node setup
        replicas: 1
        
        # Explicit single node discovery
        discovery:
          type: single-node
        
        # Node configuration
        roles: ["master", "data", "ingest"]
        
        # Resources
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        
        # Storage
        persistence:
          enabled: true
          storageClass: "gp2"
          size: 10Gi
        
        # Essential elasticsearch configuration
        esConfig:
          elasticsearch.yml: |
            discovery.type: single-node
            xpack.security.enabled: false
            xpack.monitoring.enabled: true
            
        # System settings
        sysctlInit:
          enabled: true
        
        extraEnvs:
          - name: discovery.type
            value: single-node
          - name: cluster.initial_master_nodes
            value: ""
          - name: bootstrap.memory_lock
            value: "true"