apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: elasticsearch
    helm:
      values: |
        clusterName: "elasticsearch"
        nodeGroup: "master"
        
        # Single node setup
        replicas: 1
        minimumMasterNodes: 1
        
        # Discovery settings
        discovery:
          type: single-node
        
        # Remove cluster.initial_master_nodes setting
        # Add explicit bootstrap settings
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false
            xpack.security.enabled: false
            discovery.type: single-node
            # Remove any cluster.initial_master_nodes configuration
        
        # Storage configuration
        persistence:
          enabled: true
          storageClass: "gp2"
          size: 10Gi
        
        # Resources
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi

        # System settings
        sysctlInit:
          enabled: true
          
        # Anti-affinity settings can be disabled for single node
        antiAffinity: "soft"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true