apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: elasticsearch
    helm:
      values: |
        # Disable all cluster-wide settings
        clusterName: "elasticsearch"
        masterService: "elasticsearch-master"
        
        # Set single node mode
        discovery:
          type: single-node
        
        # Remove cluster bootstrapping
        masterTerms: false
        
        # Configure node roles
        roles:
          - master
          - data
          - ingest
        
        # Basic resources
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        
        # Storage config  
        persistence:
          enabled: true
          storageClass: "gp2"
          size: 10Gi
        
        # Essential configs
        esConfig:
          elasticsearch.yml: |
            discovery.type: single-node
            xpack.security.enabled: false
            node.store.allow_mmap: false
        
        # Set explicit protocol
        protocol: http
        
        # Initialize system settings
        sysctlInit:
          enabled: true
        
        # No anti-affinity needed for single node
        antiAffinity: "soft"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true