apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: "0.24.0"
    chart: fluent-bit
    helm:
      values: |
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level info
                Parsers_File parsers.conf
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                Parser docker
                Tag kube.*
                Mem_Buf_Limit 5MB
                Skip_Long_Lines On
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master
                Port 9200
                Logstash_Format On
                Logstash_Prefix fluent-bit
                Replace_Dots On
                Retry_Limit False
                
        tolerations:
          - operator: "Exists"
        
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"