apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: "0.24.0"
    chart: fluent-bit
    helm:
      values: |
        # Service configuration
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level info
                Parsers_File parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                Parser docker
                Tag kube.*
                Mem_Buf_Limit 5MB
                Skip_Long_Lines On
                Refresh_Interval 10

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude Off

          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master
                Port 9200
                Logstash_Format On
                Logstash_Prefix fluent-bit
                Replace_Dots On
                Retry_Limit False
                Buffer_Size 1M
                Trace_Output On

        # DaemonSet configuration
        tolerations:
          - operator: Exists

        # Resource limits
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true