apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: shorturl-app.ddns.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: shorturl-tls
      hosts:
        - shorturl-app.ddns.net

spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.3
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
          config:
            ssl-redirect: true
            force-ssl-redirect: true
            use-forwarded-headers: true
          extraArgs:
            enable-ssl-passthrough: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true