apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: elasticsearch
    helm:
      values: |
        # Single node setup
        replicas: 1
        
        # Node roles correctly defined
        master: "true"
        data: "true"
        ingest: "true"
        
        # Cluster settings
        clusterName: "elasticsearch"
        nodeGroup: "master"
        
        # Discovery settings
        discovery:
          type: single-node
        
        # Storage configuration
        persistence:
          enabled: true
          storageClass: "gp2"
          accessModes:
          - ReadWriteOnce
          size: 10Gi
        
        # Resources
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        # ES Config
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false
            xpack.security.enabled: false
            discovery.type: single-node
        
        # Add tolerations
        tolerations:
          - operator: "Exists"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true