apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: elasticsearch
    helm:
      values: |
        # Force single node setup
        replicas: 1
        
        # Single node discovery
        discovery:
          type: single-node
        
        # Node configuration
        masterService: elasticsearch-master
        clusterName: elasticsearch
        
        # Storage
        persistence:
          enabled: true
          storageClass: "gp2"
          size: 10Gi
        
        # Resources
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        # Important: Configure readiness probe
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        
        # ES Config settings
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false
            xpack.security.enabled: false
            discovery.type: single-node
            cluster.initial_master_nodes: null
            cluster.routing.allocation.disk.threshold_enabled: false
            # Health check should be yellow for single node
            cluster.routing.allocation.disk.watermark.low: 93%
            cluster.routing.allocation.disk.watermark.high: 95%
        
        # Add AWS tolerations
        tolerations:
          - operator: "Exists"
        
        # Environment variables
        extraEnvs:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: discovery.type
            value: single-node
          # Expected cluster state for single node
          - name: EXPECTED_NODES
            value: "1"
          - name: MINIMUM_MASTER_NODES
            value: "1"
          # Reduce wait times
          - name: ACCEPT_DEFAULTS
            value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true