apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://cryptexlabs.github.io/helm-charts
    targetRevision: "7.17.3"  # Updated version
    chart: efk
    helm:
      values: |
        elasticsearch:
          replicas: 1
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          persistence:
            enabled: true
            storageClass: "gp2"
            size: 10Gi
          esJavaOpts: "-Xmx512m -Xms512m"
          extraEnvs:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"

        kibana:
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: kibana.yourdomain.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kibana-tls
                hosts:
                  - kibana.yourdomain.com

        fluentd:
          enabled: true
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
          tolerations:
            - operator: "Exists"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true