apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kokuwaio.github.io/helm-charts
    targetRevision: "7.17.3"
    chart: efk
    helm:
      values: |
        # Global settings
        global:
          storageClass: "gp2"
        
        # Elasticsearch settings
        elasticsearch:
          replicas: 1
          minimumMasterNodes: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          persistence:
            enabled: true
            size: 10Gi
          esConfig:
            elasticsearch.yml: |
              xpack.security.enabled: false
              discovery.type: single-node
        
        # Kibana settings
        kibana:
          enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: kibana.yourdomain.com
                paths:
                  - path: /
        
        # Fluent-bit settings
        fluent-bit:
          enabled: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true