{{- if .Values.applications.logging.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.logging.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.applications.logging.syncWave }}"
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoUrl }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: {{ .Values.applications.logging.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.logging.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}