apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "7.17.3"
    chart: elasticsearch
    helm:
      values: |
        # Single node setup
        clusterName: "elasticsearch"
        nodeGroup: "master"
        
        # Force single node
        replicas: 1
        
        # Important: Disable cluster bootstrap
        masterService: elasticsearch-master
        
        # Storage configuration
        persistence:
          enabled: true
          storageClass: "gp2"
          accessModes:
          - ReadWriteOnce
          size: 10Gi
        
        # Resources
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        # ES Config
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false
            xpack.security.enabled: false
            discovery.type: single-node
            cluster.deprecation_indexing.enabled: false
            
        # Environment variables
        extraEnvs:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: discovery.type
            value: single-node
        
        # Explicitly remove cluster bootstrap settings
        protocol: http
        clusterDiscovery: {}
        esJavaOpts: "-Xmx512m -Xms512m"
        
        # Pod security settings
        sysctlInit: true
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
        
        # Tolerations
        tolerations:
          - operator: "Exists"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true