{{- if .Values.applications.monitoring.enabled }}
# First application for CRDs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Ensures CRDs are applied first
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoUrl }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: helm/monitoring/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true

---
# Second application for Prometheus Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.monitoring.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Runs after CRDs
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoUrl }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: {{ .Values.applications.monitoring.path }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Allows ArgoCD to create the namespace if it doesn't exist
{{- end }}
