apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "48.1.1"
    chart: kube-prometheus-stack
    helm:
      values: |
        fullnameOverride: prometheus
        admissionWebhooks:
          enabled: false
          patch:
            enabled: false
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
          tls:
            enabled: false
        grafana:
          enabled: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector:
              matchLabels:
                app.kubernetes.io/instance: kube-prometheus-stack
            resources:
              requests:
                cpu: 300m
                memory: 500Mi
              limits:
                cpu: 600m
                memory: 1Gi
        crds:
          enabled: true
        alertmanager:
          enabled: true
        nodeExporter:
          enabled: true
          hostNetwork: false  # Changed to false to avoid port conflicts
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          tolerations:
            - operator: "Exists"
          service:
            port: 9100
            targetPort: 9100
        kubeStateMetrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - PruneLast=true