apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy first
spec:
  project: url-shortener
  source:
    repoURL: git@github.com:itayyoh/gitops-shorturl.git
    targetRevision: MAIN
    path: helm/url-shortener-umbrella
    helm:
      valueFiles:
        - values.yaml
        - ../values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true