{{- if .Values.applications.urlshortener.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.urlshortener.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.applications.urlshortener.syncWave }}"
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoUrl }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: {{ .Values.applications.urlshortener.path }}
    helm:
      valueFiles:
        - values.yaml
        - ../../values/{{ .Values.environment }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.urlshortener.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
