apiVersion: v2
name: monitoring
description: Monitoring stack for URL shortener
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts