apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-shortener
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: url-shortener
  namespaceSelector:
    matchNames:
      - url-shortener
  endpoints:
    - port: http
      path: /metrics
      interval: 15s