apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-shortener
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: url-shortener  # Make sure this matches your service labels
  namespaceSelector:
    matchNames:
      - url-shortener
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 14s  # Added to ensure it's less than interval