apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 55.5.0
  values:
    {{- if .Values.kubePrometheusStack }}
    {{- toYaml .Values.kubePrometheusStack | nindent 4 }}
    {{- end }}