apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-url-shortener
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ (index .Values.ingress.hosts 0).host }}
    secretName: {{ .Release.Name }}-url-shortener-tls
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          {{- range (index .Values.ingress.hosts 0).paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-url-shortener
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}