apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-url-shortener
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app: url-shortener
    app.kubernetes.io/name: {{ include "url-shortener.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "url-shortener.chart" . }}
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: url-shortener