apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-url-shortener
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: url-shortener
      app.kubernetes.io/name: {{ include "url-shortener.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}