apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-url-shortener
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: {{ .Release.Name }}