environment: dev
global:
  repoUrl: git@github.com:itayyoh/gitops-shorturl.git
  targetRevision: HEAD

applications:
  urlshortener:
    enabled: true
    namespace: url-shortener-dev

  monitoring:
    enabled: true  # Enable monitoring for development
    prometheus:
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 1
          memory: 1Gi

  logging:
    enabled: false
