environment: dev
global:
  repoUrl: git@github.com:itayyoh/gitops-shorturl.git
  targetRevision: HEAD

applications:
  urlshortener:
    enabled: true
    namespace: url-shortener-dev

  monitoring:
    enabled: false

  logging:
    enabled: false