global:
  repoUrl: git@github.com:itayyoh/gitops-shorturl.git
  targetRevision: HEAD
environment: dev

ingressNginx:
  enabled: true

applications:
  urlshortener:
    enabled: true
    name: url-shortener
    namespace: url-shortener
    path: helm/url-shortener-umbrella
    syncWave: "0"
    valuesFile: helm/values/dev.yaml

  monitoring:
    enabled: true
    name: monitoring
    namespace: monitoring
    path: helm/monitoring
    syncWave: "1"  # Deploy after url-shortener
    valuesFile: helm/values/dev.yaml  # Point to dev values or create specific for monitoring if required


  logging:
    enabled: false
    name: logging
    namespace: logging
    path: helm/logging
    syncWave: "1"  # Deploy after url-shortener
