global:
  repoUrl: https://github.com/itayyoh/gitops-shorturl.git
  targetRevision: HEAD
environment: dev

ingressNginx:
  enabled: true

applications:
  urlshortener:
    enabled: true
    name: url-shortener
    namespace: url-shortener
    path: helm/url-shortener-umbrella
    syncWave: "0"
    valuesFile: helm/values/dev.yaml

  monitoring:
    enabled: false  # Will enable later
    name: monitoring
    namespace: monitoring
    path: helm/monitoring
    syncWave: "1"  # Deploy after url-shortener

  logging:
    enabled: false  # Will enable later
    name: logging
    namespace: logging
    path: helm/logging
    syncWave: "1"  # Deploy after url-shortener

