environment: prod
global:
  repoUrl: git@github.com:itayyoh/gitops-shorturl.git
  targetRevision: HEAD

applications:
  urlshortener:
    enabled: true
    namespace: url-shortener-prod

  monitoring:
    enabled: true  # Decide whether to enable monitoring initially
    prometheus:
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"

  logging:
    enabled: false
