environment: dev
global:
  repoUrl: git@github.com:itayyoh/gitops-shorturl.git
  targetRevision: HEAD

applications:
  urlshortener:
    enabled: true
    namespace: url-shortener

  monitoring:
    enabled: true
    prometheus:
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 1
          memory: 1Gi
    nodeExporter:  # Add this section
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      hostNetwork: false  # Try disabling host network first
      service:
        port: 9100
        targetPort: 9100

  logging:
    enabled: true