apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-gp3
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Ensure this is created before other resources
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
  fsType: ext4
allowVolumeExpansion: true