apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  username: {{ index .Values.mongodb.auth.usernames 0 }}
  password: {{ index .Values.mongodb.auth.passwords 0 }}