# url-shortener-umbrella/templates/mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  username: {{ .Values.mongodb.auth.username | quote }}
  password: {{ .Values.mongodb.auth.password | quote }}
